### ISSUE TITLE
Memory leak during unlock

### ISSUE THREAD

**Issue by holiman** [bas-vk/ethsign#2]
I've been testing `ethsign` on a [USBArmory](https://inversepath.com/usbarmory) . It dies trying to unlock the key two times in a row - seems like it should either crash the first time nor not at all ? 
System info: 
```
usbarmory@usbarmory:~$ uname -a 
Linux usbarmory 4.7.2 #2 PREEMPT Wed Aug 31 13:48:50 CEST 2016 armv7l GNU/Linux

usbarmory@usbarmory:~$ free -h
             total       used       free     shared    buffers     cached
Mem:          501M        59M       441M       5.2M       5.1M        34M
-/+ buffers/cache:        20M       481M
Swap:           0B         0B         0B

usbarmory@usbarmory:~$ lscpu
Architecture:          armv7l
Byte Order:            Little Endian
CPU(s):                1
On-line CPU(s) list:   0
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             1
Model name:            ARMv7 Processor rev 5 (v7l)
CPU max MHz:           800.0000
CPU min MHz:           166.6660

```
Stack: 

```
> personal.unlockAccount(eth.accounts[0], "t")
Error: could not decrypt key with given passphrase
> personal.unlockAccount(eth.accounts[0], "t")
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x51c648, 0x16)
	/usr/local/go/src/runtime/panic.go:566 +0x78
runtime.sysMap(0x21300000, 0x10000000, 0x738fec01, 0x7aef88)
	/usr/local/go/src/runtime/mem_linux.go:230 +0x15c
runtime.(*mheap).sysAlloc(0x7a0ff8, 0x10000000, 0x10fee280)
	/usr/local/go/src/runtime/malloc.go:407 +0x144
runtime.(*mheap).grow(0x7a0ff8, 0x8000, 0x0)
	/usr/local/go/src/runtime/mheap.go:726 +0x68
runtime.(*mheap).allocSpanLocked(0x7a0ff8, 0x8000, 0x78110)
	/usr/local/go/src/runtime/mheap.go:630 +0x634
runtime.(*mheap).alloc_m(0x7a0ff8, 0x8000, 0x0, 0x10e50601, 0x5f2210)
	/usr/local/go/src/runtime/mheap.go:515 +0x138
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:579 +0x40
runtime.systemstack(0x738fedb8)
	/usr/local/go/src/runtime/asm_arm.s:261 +0xa8
runtime.(*mheap).alloc(0x7a0ff8, 0x8000, 0x0, 0x76e20101, 0x0)
	/usr/local/go/src/runtime/mheap.go:580 +0x74
runtime.largeAlloc(0x10000000, 0x76e22001, 0x25)
	/usr/local/go/src/runtime/malloc.go:774 +0xa0
runtime.mallocgc.func1()
	/usr/local/go/src/runtime/malloc.go:669 +0x34
runtime.systemstack(0x10a18000)
	/usr/local/go/src/runtime/asm_arm.s:247 +0x80
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1079

goroutine 27 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_arm.s:192 +0x4 fp=0x10f2f5ac sp=0x10f2f5a8
runtime.mallocgc(0x10000000, 0x4b8ef8, 0xf8d5501, 0x10afa000)
	/usr/local/go/src/runtime/malloc.go:670 +0xe6c fp=0x10f2f64c sp=0x10f2f5ac
runtime.makeslice(0x4b8ef8, 0x4000000, 0x0, 0x4000000, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/slice.go:57 +0x130 fp=0x10f2f674 sp=0x10f2f64c
github.com/ethereum/go-ethereum/vendor/golang.org/x/crypto/scrypt.Key(0x11294810, 0x1, 0x8, 0x112aa3c0, 0x20, 0x20, 0x40000, 0x8, 0x1, 0x20, ...)
	/home/martin/go/src/github.com/ethereum/go-ethereum/vendor/golang.org/x/crypto/scrypt/scrypt.go:235 +0x194 fp=0x10f2f700 sp=0x10f2f674
github.com/ethereum/go-ethereum/accounts/keystore.getKDFKey(0x11294710, 0xb, 0x1129a5c0, 0x40, 0x112aa340, 0x20, 0x112946d8, 0x6, 0x112aa360, 0x1129a680, ...)
	/home/martin/go/src/github.com/ethereum/go-ethereum/accounts/keystore/keystore_passphrase.go:281 +0x4cc fp=0x10f2f7dc sp=0x10f2f700
github.com/ethereum/go-ethereum/accounts/keystore.decryptKeyV3(0x1129a580, 0x11294516, 0x1, 0x0, 0x0, 0x0, 0x112947f0, 0x10, 0x10, 0x0, ...)
	/home/martin/go/src/github.com/ethereum/go-ethereum/accounts/keystore/keystore_passphrase.go:218 +0x358 fp=0x10f2f8b4 sp=0x10f2f7dc
github.com/ethereum/go-ethereum/accounts/keystore.DecryptKey(0x110f4800, 0x1eb, 0x3eb, 0x11294516, 0x1, 0x0, 0x0, 0x0)
	/home/martin/go/src/github.com/ethereum/go-ethereum/accounts/keystore/keystore_passphrase.go:179 +0x464 fp=0x10f2f964 sp=0x10f2f8b4
github.com/ethereum/go-ethereum/accounts/keystore.keyStorePassphrase.GetKey(0x10a174d0, 0x22, 0x40000, 0x1, 0x5ad733e4, 0xbef77a99, 0x66736459, 0x8502bb5b, 0xa9abaf0f, 0x10a51a40, ...)
	/home/martin/go/src/github.com/ethereum/go-ethereum/accounts/keystore/keystore_passphrase.go:82 +0xa0 fp=0x10f2f9e8 sp=0x10f2f964
github.com/ethereum/go-ethereum/accounts/keystore.(*keyStorePassphrase).GetKey(0x10ae3210, 0x5ad733e4, 0xbef77a99, 0x66736459, 0x8502bb5b, 0xa9abaf0f, 0x10a51a40, 0x70, 0x11294516, 0x1, ...)
	<autogenerated>:7 +0xe0 fp=0x10f2fa2c sp=0x10f2f9e8
github.com/ethereum/go-ethereum/accounts/keystore.(*KeyStore).getDecryptedKey(0x10a4f320, 0x5ad733e4, 0xbef77a99, 0x66736459, 0x8502bb5b, 0xa9abaf0f, 0x51634d, 0x8, 0x10a51a40, 0x70, ...)
	/home/martin/go/src/github.com/ethereum/go-ethereum/accounts/keystore/keystore.go:382 +0xf4 fp=0x10f2fa94 sp=0x10f2fa2c
github.com/ethereum/go-ethereum/accounts/keystore.(*KeyStore).TimedUnlock(0x10a4f320, 0x5ad733e4, 0xbef77a99, 0x66736459, 0x8502bb5b, 0xa9abaf0f, 0x0, 0x0, 0x0, 0x0, ...)
	/home/martin/go/src/github.com/ethereum/go-ethereum/accounts/keystore/keystore.go:340 +0x44 fp=0x10f2fb14 sp=0x10f2fa94
github.com/ethereum/go-ethereum/accounts/keystore.(*KeyStore).Unlock(0x10a4f320, 0x5ad733e4, 0xbef77a99, 0x66736459, 0x8502bb5b, 0xa9abaf0f, 0x0, 0x0, 0x0, 0x0, ...)
	/home/martin/go/src/github.com/ethereum/go-ethereum/accounts/keystore/keystore.go:317 +0x54 fp=0x10f2fb58 sp=0x10f2fb14
main.(*PersService).UnlockAccount(0x10a22d78, 0x5ad733e4, 0xbef77a99, 0x66736459, 0x8502bb5b, 0xa9abaf0f, 0x11294516, 0x1, 0x0, 0x0, ...)
	/home/martin/go/src/github.com/bas-vk/ethsign/services.go:36 +0x90 fp=0x10f2fbc8 sp=0x10f2fb58
runtime.call64(0x112452e0, 0x10a22dd8, 0x1124c9c0, 0x30, 0x24)
	/usr/local/go/src/runtime/asm_arm.s:431 +0x68 fp=0x10f2fc0c sp=0x10f2fbc8
reflect.Value.call(0x10a6e9b0, 0x10a22dd8, 0x13, 0x514aab, 0x4, 0x1124c900, 0x4, 0x4, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:434 +0xd68 fp=0x10f2fdb4 sp=0x10f2fc0c
reflect.Value.Call(0x10a6e9b0, 0x10a22dd8, 0x13, 0x1124c900, 0x4, 0x4, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:302 +0x84 fp=0x10f2fde4 sp=0x10f2fdb4
github.com/ethereum/go-ethereum/rpc.(*Server).handle(0x10b03c40, 0x7724a8, 0x10c96880, 0x773768, 0x10a17920, 0x1129a480, 0x0, 0x0, 0x1)
	/home/martin/go/src/github.com/ethereum/go-ethereum/rpc/server.go:328 +0xc74 fp=0x10f2ff1c sp=0x10f2fde4
github.com/ethereum/go-ethereum/rpc.(*Server).exec(0x10b03c40, 0x7724a8, 0x10c96880, 0x773768, 0x10a17920, 0x1129a480)
	/home/martin/go/src/github.com/ethereum/go-ethereum/rpc/server.go:350 +0x1c0 fp=0x10f2ff80 sp=0x10f2ff1c
github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest.func2(0x10c924e0, 0x10b03c40, 0x10c94bf0, 0x773768, 0x10a17920, 0x10f08f90, 0x1, 0x1, 0x0)
	/home/martin/go/src/github.com/ethereum/go-ethereum/rpc/server.go:223 +0x110 fp=0x10f2ffa4 sp=0x10f2ff80
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm.s:998 +0x4 fp=0x10f2ffa4 sp=0x10f2ffa4
created by github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest
	/home/martin/go/src/github.com/ethereum/go-ethereum/rpc/server.go:225 +0xad0

goroutine 1 [chan receive]:
github.com/ethereum/go-ethereum/internal/jsre.(*JSRE).Evaluate(0x10b03e80, 0x112a0e40, 0x2d, 0x76f9e0, 0x10a220d8, 0x0, 0x0)
	/home/martin/go/src/github.com/ethereum/go-ethereum/internal/jsre/jsre.go:319 +0x150
github.com/ethereum/go-ethereum/console.(*Console).Evaluate(0x10c586c0, 0x112a0e40, 0x2d, 0x0, 0x0)
	/home/martin/go/src/github.com/ethereum/go-ethereum/console/console.go:282 +0x84
github.com/ethereum/go-ethereum/console.(*Console).Interactive(0x10c586c0)
	/home/martin/go/src/github.com/ethereum/go-ethereum/console/console.go:354 +0x5e0
main.main()
	/home/martin/go/src/github.com/bas-vk/ethsign/main.go:46 +0x2ac

[...]
``` 
LMK if you want more stack trace...

**Comment by holiman** [comment]
Actually (and not surprising), same thing on geth 1.6.1. But not until after the third attempt: 
```
usbarmory@usbarmory:~/geth-linux-arm7-1.6.1-021c3c28$ ./geth console
INFO [08-31|15:38:50] Starting peer-to-peer node               instance=Geth/v1.6.1-stable-021c3c28/linux-arm/go1.8.1
INFO [08-31|15:38:50] Allocated cache and file handles         database=/home/usbarmory/.ethereum/geth/chaindata cache=128 handles=1024
INFO [08-31|15:38:51] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Engine: ethash}"
INFO [08-31|15:38:51] Disk storage enabled for ethash caches   dir=/home/usbarmory/.ethereum/geth/ethash count=3
INFO [08-31|15:38:51] Disk storage enabled for ethash DAGs     dir=/home/usbarmory/.ethash               count=2
INFO [08-31|15:38:51] Initialising Ethereum protocol           versions="[63 62]" network=1
INFO [08-31|15:38:51] Loaded most recent local header          number=0 hash=d4e567…cb8fa3 td=17179869184
INFO [08-31|15:38:51] Loaded most recent local full block      number=0 hash=d4e567…cb8fa3 td=17179869184
INFO [08-31|15:38:51] Loaded most recent local fast block      number=0 hash=d4e567…cb8fa3 td=17179869184
INFO [08-31|15:38:51] Starting P2P networking 
INFO [08-31|15:38:53] RLPx listener up                         self=enode://21a327e4e8e1ca918ce86974fe6f1f9029f464970866c6baf5c4a04badb2924c80df7ede967d5f047c7bb43ba8597fc48059a3e5434ef95c81aafb058ae66f0b@[::]:30303
INFO [08-31|15:38:53] IPC endpoint opened: /home/usbarmory/.ethereum/geth.ipc 
Welcome to the Geth JavaScript console!

instance: Geth/v1.6.1-stable-021c3c28/linux-arm/go1.8.1
coinbase: 0xe433d75a997af7be596473665bbb02850fafaba9
at block: 0 (Thu, 01 Jan 1970 00:00:00 UTC)
 datadir: /home/usbarmory/.ethereum
 modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

> personal.unlockAccount(eth.accounts[0],"x")
Error: could not decrypt key with given passphrase
> personal.unlockAccount(eth.accounts[0],"x")
Error: could not decrypt key with given passphrase
> personal.unlockAccount(eth.accounts[0],"x")
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x8bc6b6, 0x16)
	/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/runtime/panic.go:596 +0x70
runtime.sysMap(0x25600000, 0x10000000, 0x730fec01, 0xed5930)
	/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/runtime/mem_linux.go:227 +0xb0
runtime.(*mheap).sysAlloc(0xec7bc8, 0x10000000, 0x50368)
	/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/runtime/malloc.go:428 +0x2bc
runtime.(*mheap).grow(0xec7bc8, 0x8000, 0x0)
	/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/runtime/mheap.go:774 +0x48
runtime.(*mheap).allocSpanLocked(0xec7bc8, 0x8000, 0xd7c8)
	/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/runtime/mheap.go:678 +0x468
runtime.(*mheap).alloc_m(0xec7bc8, 0x8000, 0x0, 0x1, 0x1f500)
	/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/runtime/mheap.go:562 +0xdc
runtime.(*mheap).alloc.func1()
	/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/runtime/mheap.go:627 +0x3c
runtime.systemstack(0x730fedc0)
	/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/runtime/asm_arm.s:278 +0xa8
runtime.(*mheap).alloc(0xec7bc8, 0x8000, 0x0, 0x50101, 0xec8ea0)
	/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/runtime/mheap.go:628 +0x60
runtime.largeAlloc(0x10000000, 0x76dba001, 0x25)
	/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/runtime/malloc.go:795 +0x78
runtime.mallocgc.func1()
	/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/runtime/malloc.go:690 +0x30
runtime.systemstack(0x1121a000)
	/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/runtime/asm_arm.s:264 +0x80
runtime.mstart()
	/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/runtime/proc.go:1132

goroutine 205 [running]:
runtime.systemstack_switch()
	/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/runtime/asm_arm.s:209 +0x4 fp=0x135b980c sp=0x135b9808
runtime.mallocgc(0x10000000, 0x7bd640, 0x114dba01, 0x125e7000)
	/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/runtime/malloc.go:691 +0x9dc fp=0x135b9864 sp=0x135b980c
runtime.makeslice(0x7bd640, 0x4000000, 0x4000000, 0x125e7000, 0x200, 0x200)
	/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/runtime/slice.go:54 +0x68 fp=0x135b9888 sp=0x135b9864
github.com/ethereum/go-ethereum/vendor/golang.org/x/crypto/scrypt.Key(0x12958e78, 0x1, 0x8, 0x1143a780, 0x20, 0x20, 0x40000, 0x8, 0x1, 0x20, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/golang.org/x/crypto/scrypt/scrypt.go:235 +0x14c fp=0x135b98e8 sp=0x135b9888
github.com/ethereum/go-ethereum/accounts/keystore.getKDFKey(0x12958dc0, 0xb, 0x114dba00, 0x40, 0x1143a700, 0x20, 0x12958dd0, 0x6, 0x1143a720, 0x114dba80, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/accounts/keystore/keystore_passphrase.go:281 +0x574 fp=0x135b9970 sp=0x135b98e8
github.com/ethereum/go-ethereum/accounts/keystore.decryptKeyV3(0x114db9c0, 0x12958c2e, 0x1, 0x77a9a8, 0x114db9c0, 0x0, 0x0, 0x0, 0xc, 0x121bc690, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/accounts/keystore/keystore_passphrase.go:218 +0x20c fp=0x135b9a20 sp=0x135b9970
github.com/ethereum/go-ethereum/accounts/keystore.DecryptKey(0x113a6000, 0x1eb, 0x3eb, 0x12958c2e, 0x1, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/accounts/keystore/keystore_passphrase.go:179 +0x16c fp=0x135b9a84 sp=0x135b9a20
github.com/ethereum/go-ethereum/accounts/keystore.keyStorePassphrase.GetKey(0x11379e30, 0x22, 0x40000, 0x1, 0x5ad733e4, 0xbef77a99, 0x66736459, 0x8502bb5b, 0xa9abaf0f, 0x11394d20, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/accounts/keystore/keystore_passphrase.go:82 +0x60 fp=0x135b9ae8 sp=0x135b9a84
github.com/ethereum/go-ethereum/accounts/keystore.(*keyStorePassphrase).GetKey(0x11566670, 0x5ad733e4, 0xbef77a99, 0x66736459, 0x8502bb5b, 0xa9abaf0f, 0x11394d20, 0x70, 0x12958c2e, 0x1, ...)
	<autogenerated>:7 +0xa0 fp=0x135b9b2c sp=0x135b9ae8
github.com/ethereum/go-ethereum/accounts/keystore.(*KeyStore).getDecryptedKey(0x11539ef0, 0x5ad733e4, 0xbef77a99, 0x66736459, 0x8502bb5b, 0xa9abaf0f, 0x892d99, 0x8, 0x11394d20, 0x70, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/accounts/keystore/keystore.go:382 +0xc4 fp=0x135b9b88 sp=0x135b9b2c
github.com/ethereum/go-ethereum/accounts/keystore.(*KeyStore).TimedUnlock(0x11539ef0, 0x5ad733e4, 0xbef77a99, 0x66736459, 0x8502bb5b, 0xa9abaf0f, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/accounts/keystore/keystore.go:340 +0x44 fp=0x135b9bfc sp=0x135b9b88
github.com/ethereum/go-ethereum/internal/ethapi.(*PrivateAccountAPI).UnlockAccount(0x11341250, 0x5ad733e4, 0xbef77a99, 0x66736459, 0x8502bb5b, 0xa9abaf0f, 0x12958c2e, 0x1, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/internal/ethapi/api.go:307 +0x13c fp=0x135b9c78 sp=0x135b9bfc
runtime.call64(0x123be760, 0x115601c0, 0x11379da0, 0x30, 0x24)
	/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/runtime/asm_arm.s:451 +0x68 fp=0x135b9cbc sp=0x135b9c78
reflect.Value.call(0x1139a000, 0x115601c0, 0x13, 0x88d1ae, 0x4, 0x11379470, 0x4, 0x4, 0x2, 0x40001, ...)
	/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/reflect/value.go:434 +0x8d8 fp=0x135b9e64 sp=0x135b9cbc
reflect.Value.Call(0x1139a000, 0x115601c0, 0x13, 0x11379470, 0x4, 0x4, 0x3, 0x3, 0x85d14)
	/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/reflect/value.go:302 +0x74 fp=0x135b9e94 sp=0x135b9e64
github.com/ethereum/go-ethereum/rpc.(*Server).handle(0x11308ac0, 0xdf0850, 0x113fae80, 0xdf2d08, 0x1157d170, 0x114db840, 0x112125e0, 0x0, 0x389dd4)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/server.go:328 +0x554 fp=0x135b9f6c sp=0x135b9e94
github.com/ethereum/go-ethereum/rpc.(*Server).exec(0x11308ac0, 0xdf0850, 0x113fae80, 0xdf2d08, 0x1157d170, 0x114db840)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/server.go:350 +0x154 fp=0x135b9fa0 sp=0x135b9f6c
github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest.func2(0x113b79a0, 0x11308ac0, 0x11561ff8, 0xdf2d08, 0x1157d170, 0x11401d58, 0x1, 0x1, 0x0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/server.go:223 +0x88 fp=0x135b9fc4 sp=0x135b9fa0
runtime.goexit()
	/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/runtime/asm_arm.s:1017 +0x4 fp=0x135b9fc4 sp=0x135b9fc4
created by github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/server.go:225 +0x284

```

**Comment by holiman** [comment]
So this is probably ok, since the default scrypt requires about 268M. however, geth supports `--lightkdf`, which uses different params :` {"dklen":32,"n":4096,"p":6,"r":8"}`, bringing it down from 268M to ~4.2M, if I counted correctly.

However, that's a flag to `geth account new` - I don't think it's accessible from javascript, and it's not implemented in `ethsign`. So I propose you add it as a flag to ethsign, or make it settable via js.

**Comment by bas-vk** [comment]
Cool to hear that you are using this!

I just merged support for the `--lightkdf` flag that has the same semantics as in geth, `ethsign --lightkdf`.
